name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter pub get
      # We have warnings due to .env file that is not checked in, but is in pubspec.yaml:assets
      # Note: --no-fatal-warnings still exits with a 1, even though there are just warnings.
      # - run: flutter analyze --no-fatal-warnings
      - run: flutter test
#      - run: flutter test --coverage
#      - uses: codecov/codecov-action@v1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
